//
//  MysticShapesAnimalsKit.h
//  ProjectName
//
//  Created by Travis Weerts on 12/4/15.
//  Copyright (c) 2015 Mystic. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "MysticDrawKit.h"
#import "MysticChoice.h"


@interface MysticShapesAnimalsKit : MysticDrawKit

// Drawing Methods
+ (NSDictionary *)drawElkWithOptions: (MysticChoice*)choice;
+ (NSDictionary *)drawEagleWithOptions: (MysticChoice*)choice;
+ (NSDictionary *)drawDeerWithOptions: (MysticChoice*)choice;
+ (NSDictionary *)drawBuffaloWithOptions: (MysticChoice*)choice;

@end
