//
//  MysticShapesKit.h
//  Mystic
//
//  Created by Travis Weerts on 10/26/15.
//  Copyright (c) 2015 Mystic. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "MysticConstants.h"
#import "MysticDrawKit.h"
#import "MysticShapesAnimalsKit.h"
#import "MysticShapesDecorativeKit.h"
// #import "MysticShapesLinesKit.h"
//#import "MysticShapesTexturesKit.h"


@interface MysticShapesKit : MysticDrawKit


// Drawing Methods
//+ (NSDictionary *)drawDottedLineWithOptions:(MysticChoice *)choice;
//+ (NSDictionary *)drawLine2WithOptions:(MysticChoice *)choice;
//+ (NSDictionary *)drawSampleShapeWithOptions:(MysticChoice *)choice;
//+ (NSDictionary *)drawSacred1WithOptions:(MysticChoice *)choice;
//+ (NSDictionary *)drawSacredSpiralWithOptions:(MysticChoice *)choice;
//+ (NSDictionary *)drawSacredTriangleWithOptions:(MysticChoice *)choice;
//+ (NSDictionary *)drawSacredSextagonWithOptions:(MysticChoice *)choice;
//+ (NSDictionary *)drawSacredIndianStarCircleWithOptions:(MysticChoice *)choice;

@end
